spring:
  application:
    name: notification
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        use-default-aws-credentials-chain: true

sqs:
  queue:
    order: ${SQS_ORDER_QUEUE_NAME}