name: SonarCloud Analysis
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'inventory/**'
      - 'notification/**'
      - 'order/**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  sonar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['inventory', 'notification', 'order']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=LucasMartins007_event-driven-architeture-example_${{ matrix.service }} \
            -Dsonar.projectName="${{ matrix.service }}"